/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/trampoline.glb 
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/trampoline-052aaef6c5c34c5bac94607bcc12d2f9
Title: Trampoline
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { ItemSpawner } from "../../helpers/item-spwaner";
import { ItemSelector } from "../../helpers/item-selcetor";
import RemoveLastItem from "../../helpers/delete-last-item";

export default function Trampoline({ currentItem }) {
  const [items, setItems] = useState([]);

  return (
    <>
      <ItemSpawner
        items={items}
        setItems={setItems}
        model={"trampoline"}
        currentItem={currentItem}
      />
      <ItemSelector items={items} setItems={setItems} />
      {currentItem === "trampoline" && (
        <RemoveLastItem items={items} setItems={setItems} />
      )}
    </>
  );
}

useGLTF.preload("/Models/trampoline.glb");
