/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/trampoline.glb 
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/trampoline-052aaef6c5c34c5bac94607bcc12d2f9
Title: Trampoline
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { ObejctSpawner } from "../../helpers/object-spwaner";
import { ObjectSelector } from "../../helpers/object-selcetor";
import RemoveLastItem from "../../helpers/delete-last-object";

export default function Trampoline({ showObject }) {
  const [objects, setObjects] = useState([]);

  return (
    <>
      <ObejctSpawner
        objects={objects}
        setObjects={setObjects}
        model={"trampoline"}
        showObject={showObject}
      />
      <ObjectSelector cubes={objects} setCubes={setObjects} />
      {showObject === "trampoline" && (
        <RemoveLastItem items={objects} setItems={setObjects} />
      )}
    </>
  );
}

useGLTF.preload("/trampoline.glb");
