/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/markerMan.glb 
*/

import React, { useEffect, useState } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useBox } from "@react-three/cannon";

export function markerManAnimations(actions, arduinoButtonPressed) {
  const sittingIdle = actions["SITTINGIDLE"];
  const sittingIdleTime = sittingIdle.getClip().duration * 1000 - 500;

  const scare = actions["SCARE"];
  const scareTime = scare.getClip().duration * 1000 - 500;

  const sitting2 = actions["SITTING2"];
  const sitting2Time = sitting2.getClip().duration * 1000 - 500;

  const tripp = actions["TRIP"];
  const trippTime = tripp.getClip().duration * 1000 - 500;

  const layingIdle = actions["LAYING"];
  const layingIdleTime = layingIdle.getClip().duration * 1000 - 500;

  const layingLooking = actions["LAYINGLOKKINGG"];
  const layingLookingTime = layingLooking.getClip().duration * 1000 - 500;

  const waking = actions["WAKING"];
  const wakingTime = waking.getClip().duration * 1000 - 500;

  const getup = actions["GETUP"];
  const getupTime = getup.getClip().duration * 1000 - 500;

  const looking = actions["LOOKING"];
  const lookingTime = looking.getClip().duration * 1000 - 500;

  const stomp = actions["STOMP"];
  const stompTime = stomp.getClip().duration * 1000 * 2 - 1000;

  const jump = actions["JUMP"];
  const jumpTime = jump.getClip().duration * 1000 - 500;

  const fistPump = actions["FISTPUMP"];
  const fistPumpTime = fistPump.getClip().duration * 1000 - 500;

  const dance = actions["DANCE"];
  const danceTime = dance.getClip().duration * 1000 - 500;

  const dance2 = actions["DANCE2"];
  const dance2Time = dance2.getClip().duration * 1000 - 500;

  //   sittingIdle.play();

  //   if (actions && arduinoButtonPressed) {
  //     sittingIdle.fadeOut(0.5);
  //     setTimeout(() => {
  //       scare.fadeIn(0.5).play();
  //       setTimeout(() => {
  //         scare.fadeOut(0.5);
  //         tripp.fadeIn(0.5).play();
  //         setTimeout(() => {
  //           tripp.fadeOut(0.5);
  //           layingIdle.fadeIn(0.5).play();
  //         }, trippTime);
  //       }, scareTime);
  //     }, 0.5);
  //   }

  layingIdle.play();

  if (actions && arduinoButtonPressed) {
    layingIdle.fadeOut(0.5);
    setTimeout(() => {
      layingLooking.fadeIn(0.5).play();
      setTimeout(() => {
        layingLooking.fadeOut(0.5);
        waking.fadeIn(0.5).play();
        setTimeout(() => {
          waking.fadeOut(0.5);
          getup.fadeIn(0.5).play();
          setTimeout(() => {
            getup.fadeOut(0.5);
            stomp.fadeIn(0.5).play();
            setTimeout(() => {
              stomp.fadeOut(0.5);
              jump.fadeIn(0.5).play();
              setTimeout(() => {
                jump.fadeOut(0.5);
                looking.fadeIn(0.5).play();
                setTimeout(() => {
                  looking.fadeOut(0.5);
                  fistPump.fadeIn(0.5).play();
                  setTimeout(() => {
                    fistPump.fadeOut(0.5);
                    dance2.fadeIn(0.5).play();
                  }, fistPumpTime);
                }, lookingTime);
              }, jumpTime);
            }, stompTime);
          }, getupTime);
        }, wakingTime);
      }, layingLookingTime);
    }, 0.5);
  }
}

useGLTF.preload("/markerMan.glb");
