/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/party_cannon.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/party_cannon.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.123, -0.547, -0.047]} rotation={[0, 0, -3.133]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Cannon_Wheels} position={[-2.128, -0.528, 0.047]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Cannon_Body} position={[-2.128, -0.528, 0.047]} />
      </group>
    </group>
  )
}

useGLTF.preload('/party_cannon.glb')
