/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/markerMan.glb 
*/

import React, { useEffect, useState } from "react";
import { useBox } from "@react-three/cannon";
import { ButtonModel } from "./Button";

export function GameBoxShelf({ position, rotation, size }) {
  const ref = React.useRef();
  const [physicRef, physicApi] = useBox(() => ({
    type: "Static",
    args: size,
    position: [position],
    rotation: [rotation],
  }));

  useEffect(() => {
    physicApi.position.set(position[0], position[1] - 0.07, position[2]);
    physicApi.rotation.set(...rotation);
  }, [position, physicApi.position, physicApi]);

  return (
    <group>
      {" "}
      <mesh position={[0, -0.07, 0]}>
        <boxGeometry args={size} />
        <meshStandardMaterial color="blue" transparent={true} opacity={0.0} />
      </mesh>
      <ButtonModel />
    </group>
  );
}
