/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/marker-man.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function MarkerManMiniModel({ scale = 0.1 }) {
  const group = React.useRef();
  const { scene, animations: loadedAnimations } = useGLTF("/marker-man.glb");
  //console.log("Loaded animations:", loadedAnimations);

  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(loadedAnimations, group);

  React.useEffect(() => {
    if (actions) {
      actions["SITTINGIDLE"].play();
    }
  }, [actions]);

  return (
    <group ref={group} scale={scale} dispose={null}>
      <group name="Scene">
        <group
          name="MocapGuy_HiRes_Meshes"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group name="Armature007" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="MocapGuy_Body">
            <skinnedMesh
              name="MocapGuy_Body_1"
              geometry={nodes.MocapGuy_Body_1.geometry}
              material={materials.Body_MAT}
              skeleton={nodes.MocapGuy_Body_1.skeleton}
            />
            <skinnedMesh
              name="MocapGuy_Body_2"
              geometry={nodes.MocapGuy_Body_2.geometry}
              material={materials.Reflectors}
              skeleton={nodes.MocapGuy_Body_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="MocapGuy_BrowsLashes"
            geometry={nodes.MocapGuy_BrowsLashes.geometry}
            material={materials.Brows_MAT}
            skeleton={nodes.MocapGuy_BrowsLashes.skeleton}
          />
          <skinnedMesh
            name="MocapGuy_Caruncula"
            geometry={nodes.MocapGuy_Caruncula.geometry}
            material={materials.Body_MAT}
            skeleton={nodes.MocapGuy_Caruncula.skeleton}
          />
          <skinnedMesh
            name="MocapGuy_Eyes"
            geometry={nodes.MocapGuy_Eyes.geometry}
            material={materials.Eyes_MAT}
            skeleton={nodes.MocapGuy_Eyes.skeleton}
          />
          <group name="MocapGuy_Hat">
            <skinnedMesh
              name="MocapGuy_Hat_1"
              geometry={nodes.MocapGuy_Hat_1.geometry}
              material={materials.Body_MAT}
              skeleton={nodes.MocapGuy_Hat_1.skeleton}
            />
            <skinnedMesh
              name="MocapGuy_Hat_2"
              geometry={nodes.MocapGuy_Hat_2.geometry}
              material={materials.Reflectors}
              skeleton={nodes.MocapGuy_Hat_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="MocapGuy_Teeth"
            geometry={nodes.MocapGuy_Teeth.geometry}
            material={materials.Body_MAT}
            skeleton={nodes.MocapGuy_Teeth.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/marker-man.glb");
