/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/party_cannon.glb
*/
import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useSphere, useTrimesh } from "@react-three/cannon";
import { ObejctSpawner } from "../../helpers/object-spwaner";
import { ObjectSelector } from "../../helpers/object-selcetor";
import RemoveLastItem from "../../helpers/delete-last-object";
import { ArrowHelper, Vector3 } from "three";
import { Scene } from "three/src/Three.js";
import { ButtonModel } from "../physical-game-box/Button";

export function CannonModel({ onRef, position, rotation }) {
  const ref = useRef();
  const { nodes, materials } = useGLTF("/party_cannon.glb");

  const wheelGeometry = nodes.Object_4.geometry;
  const bodyGeometry = nodes.Object_5.geometry;

  const data1 = nodes.Object_4.geometry.attributes.position.array;
  const data2 = nodes.Object_4.geometry.index.array;
  const data3 = nodes.Object_5.geometry.attributes.position.array;
  const data4 = nodes.Object_5.geometry.index.array;

  const [wheelRef, wheelApi] = useTrimesh(
    () => ({
      type: "Static",
      mass: 2,
      rotation: rotation,
      position: position,
      args: [data1, data2],
    }),
    useRef()
  );

  const [bodyRef, bodyApi] = useTrimesh(
    () => ({
      type: "Static",
      mass: 2,
      rotation: [rotation[0], rotation[1], rotation[2]],
      position: position,
      args: [data3, data4],
    }),
    useRef()
  );

  const [sphereRef, sphereApi] = useSphere(() => ({
    mass: 0,
    position: [position[0] + 0.25, position[1] + 0.3, position[2] + 0.04],
    type: "Dynamic",
    rotation,
    args: [0.03],

    ccdSweptSphereRadius: 0.05,
  }));

  useEffect(() => {
    if (bodyApi.position && wheelApi.position && sphereApi.position) {
      bodyApi.position.set(...position);
      wheelApi.position.set(...position);
      sphereApi.position.set(position[0], position[1] + 0.1, position[2]);
    }
    if (bodyApi.position && wheelApi.rotation) {
      bodyApi.rotation.set(rotation[0], rotation[1], rotation[2] - 3.133);
      wheelApi.rotation.set(rotation[0], rotation[1], rotation[2] - 3.133);
      sphereApi.rotation.set(rotation[0], rotation[1], rotation[2] - 3.133);
    }

    const dir = new THREE.Vector3(
      -1,
      Math.tan(THREE.MathUtils.degToRad(-20)),
      0
    ).normalize();
    const arrowHelper = new ArrowHelper(
      dir,
      new THREE.Vector3(0, -0.12, 0),
      1,
      0xffff00
    );

    bodyRef.current.add(arrowHelper);
  }, [position, rotation, wheelApi, bodyApi]);

  useEffect(() => {
    onRef(ref);
  }, [ref, onRef]);

  return (
    <group dispose={null}>
      <group ref={ref}>
        <mesh
          geometry={wheelGeometry}
          material={materials.Cannon_Wheels}
          // material-transparent={true}
          // material-opacity={0.2}
          ref={wheelRef}
        />
        <mesh
          geometry={bodyGeometry}
          material={materials.Cannon_Body}
          // material-transparent={true}
          // material-opacity={0.2}
          ref={bodyRef}
        />
        <mesh ref={sphereRef}>
          <sphereGeometry args={[0.03, 16, 16]} />
          <meshStandardMaterial color={"yellow"} />
        </mesh>
      </group>
    </group>
  );
}

export default function Cannon({ showObject }) {
  const [objects, setObjects] = useState([]);

  return (
    <>
      <ObejctSpawner
        objects={objects}
        setObjects={setObjects}
        model={"cannon"}
        showObject={showObject}
      />
      <ObjectSelector cubes={objects} setCubes={setObjects} isGLTF={true} />
      {showObject === "cannon" && (
        <RemoveLastItem items={objects} setItems={setObjects} />
      )}
    </>
  );
}

useGLTF.preload("/party_cannon.glb");
