/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/books.glb 
Author: VR.Space (https://sketchfab.com/vrspace01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/variety-of-books-9ecd80af3b7e4cd59efb4c141511a55b
Title: Variety of Books
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Books(props) {
  const { nodes, materials } = useGLTF("/books.glb");
  return (
    <group position={[0.18, 0.325, -0.1]} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Cube_books_0.geometry}
          material={materials.books}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={9}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/books.glb");
