/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/vintage_desk_lamp.glb 
Author: Eliza Jacobs (https://sketchfab.com/ElizaJacobs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-desk-lamp-a4c4b5d53364473bb3c71b33963652b3
Title: Vintage Desk lamp
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vintage_desk_lamp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Desk_Lamp1_lambert1_0.geometry} material={materials.lambert1} position={[-0.2, -0.465, 0.651]} rotation={[0, Math.PI / 4, 0]} scale={0.015} />
    </group>
  )
}

useGLTF.preload('/vintage_desk_lamp.glb')
