/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/Models/board_school.glb 
Author: adventurer (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/board-school-9424811b5b9a4d788973807acef91ca4
Title: Board School
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { DirectionalLight, SpotLight } from "three";

export function SchoolBoard({ position = [0, 0, 0] }) {
  const { nodes, materials } = useGLTF("/Models/board_school.glb");
  const spotlight = useMemo(() => new SpotLight("#fff"), []);
  const directionalLight = useMemo(() => new DirectionalLight("#FFF5E1"), []);
  return (
    <group position={position}>
      <pointLight
        position={[1, 0.5, 1]} // Position des Lichts in der Szene
        intensity={5} // Helligkeit
        distance={1.7} // Reichweite des Lichts
        decay={2} // Lichtabfall mit der Entfernung
        color={"#ffddaa"} // Lichtfarbe (optional für warmes Licht)
        castShadow
      />
      <pointLight
        position={[0, 0.5, 1]} // Position des Lichts in der Szene
        intensity={5} // Helligkeit
        distance={1.7} // Reichweite des Lichts
        decay={2} // Lichtabfall mit der Entfernung
        color={"#ffddaa"} // Lichtfarbe (optional für warmes Licht)
        castShadow
      />
      <pointLight
        position={[-1, 0.5, 1]} // Position des Lichts in der Szene
        intensity={5} // Helligkeit
        distance={1.7} // Reichweite des Lichts
        decay={2} // Lichtabfall mit der Entfernung
        color={"#ffddaa"} // Lichtfarbe (optional für warmes Licht)
        castShadow
      />
      <group dispose={null}>
        <group scale={0.01}>
          <mesh
            geometry={nodes.board_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[0, 0, -0]}
            rotation={[0, -Math.PI, Math.PI / 2]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Models/board_school.glb");
