/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/kallax_shelf.glb 
Author: CN Entertainment (https://sketchfab.com/cn-entertainment)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kallax-shelf-e2d30124563947608a500df26f77b659
Title: Kallax Shelf
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useBox } from "@react-three/cannon";
import * as THREE from "three";
export function Shelf() {
  // Laden der Textur
  const newTexture = useTexture("/Textures/metal.jpg");

  // Erstellen eines neuen Materials mit der Textur
  const woodMaterial = new THREE.MeshStandardMaterial({ map: newTexture });

  const { nodes, materials } = useGLTF("/Models/kallax_shelf.glb");
  return (
    <group dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Cube_White_0.geometry}
          material={
            new THREE.MeshStandardMaterial({
              color: "#4169E1",
              roughness: 0.7,
              metalness: 0.3,
            })
          }
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Models/kallax_shelf.glb");
