/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/old_radio.glb 
Author: Gunnar Correa (https://sketchfab.com/gunnarcorrea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-radio-2c1eb3eaa58d4d60b0fbdd38a08833d5
Title: Old radio
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Radio() {
  const { nodes, materials } = useGLTF("/old_radio.glb");
  return (
    <group dispose={null} position={[-0.17, 0.365, -0.07]}>
      <mesh
        geometry={nodes.LowPolyRadio_Material_0.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.000077}
      />
    </group>
  );
}

useGLTF.preload("/old_radio.glb");
