/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/plant.glb 
Author: Blizzy (https://sketchfab.com/jeffbas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pothos-plant-175142c4942b42169455eb20c4033c9d
Title: Pothos Plant
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Plant(props) {
  const { nodes, materials } = useGLTF("/plant.glb");
  return (
    <group position={[0.23, 0.65, 0.05]} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.ivy_2_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.ivy_1_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          geometry={nodes.grass_lambert9_0.geometry}
          material={materials.lambert9}
        />
        <mesh
          geometry={nodes.pot_lambert5_0.geometry}
          material={materials.lambert5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/plant.glb");
