/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/Models/spotlight.glb 
Author: dayoung.ko (https://sketchfab.com/dayoung.ko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spotlight-7b58b6ddcd2541e783750ccd266ec51c
Title: Spotlight
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Spotlight({ rotation = [0, -Math.PI / 2, Math.PI] }) {
  const { nodes, materials } = useGLTF("/Models/spotlight.glb");
  return (
    <group
      dispose={null}
      scale={[0.015, 0.015, 0.015]}
      position={[0, 0, 0]}
      rotation={rotation}
    >
      <group
        position={[0, 0, 0]}
        rotation={[1.467, -0.956, -0.134]}
        scale={[0.162, 2.235, 0.162]}
      >
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Material.067"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Material.066"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Material.065"]}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.material_0}
        position={[0.512, -3.565, 0]}
        rotation={[0, -0.16, 0]}
        scale={[2.077, 0.668, 2.077]}
      />
    </group>
  );
}

useGLTF.preload("/spotlight.glb");
