/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/vinyl_record.glb 
Author: freddy1231 (https://sketchfab.com/freddy1231)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/12-vinyl-record-6805e433c87f4f1b8be388d5676a50e7
Title: 12" Vinyl Record
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function VinylRecord({ position = [-0.17, -0.307, 0] }) {
  const { nodes, materials } = useGLTF(
    "/Models/shelf-decoration//vinyl_record.glb"
  );
  return (
    <group position={position} dispose={null}>
      <mesh
        geometry={
          nodes["#REC0002_33_Highway_To_Hell_#REC0002_Textures_0"].geometry
        }
        material={materials.REC0002_Textures}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.8}
      />
    </group>
  );
}

useGLTF.preload("/Models/shelf-decoration//vinyl_record.glb");
