/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/notebook.glb 
Author: NoobiePie (https://sketchfab.com/NoobiePie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-bookdiary-1a5b93387fb24eb49db34b560794055c
Title: Low Poly Book/Diary
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Notebook({ position, rotation }) {
  const { nodes, materials } = useGLTF("/notebook.glb");
  const newTexture = useTexture("/Textures/bookTexture.jpg");
  const bookMaterial = new THREE.MeshStandardMaterial({ map: newTexture });
  return (
    <group position={position} rotation={rotation}>
      <group rotation={[-1.571, 0, 0]} scale={0.07}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, -11.5, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cover_Cover_0.geometry}
              material={bookMaterial}
            />
            <mesh
              geometry={nodes.Cover_Join_0.geometry}
              material={bookMaterial}
            />
          </group>
          <mesh
            geometry={nodes.Pages_Material_0.geometry}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <meshToonMaterial color={"#e2e5de"} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/notebook.glb");
