/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/notebook2.glb 
Author: Hamza.006 (https://sketchfab.com/Hamza.006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-c5be32eebbdd4cfe94ef9ebbb21e09cf
Title: Book
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Notebook2(props) {
  const { nodes, materials } = useGLTF(
    "/Models/shelf-decoration/notebook2.glb"
  );
  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.pCube1_lambert2_0.geometry}
        material={materials.lambert2}
        rotation={[-Math.PI, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/Models/shelf-decoration/notebook2.glb");
